// import './library.js';
import './js/fetchPopular';
import 'animate.css/animate.css';
import './scripts/render-list';
import './scripts/genres-list';
import './scripts/keyword/seachKeyword';
import './scripts/trailer';
import './js/fetchPopular';
import './scripts/btnToTop';
import './scripts/modalFilms';
// import './js/modalFilm';
import './scripts/team-modal';
import './scripts/switchTheme';
// import './js/spinner';
import './scripts/pagination';
import './scripts/filter';
